server:
  port: 8080
  cors_origins: ["*"]

routes:
  google_routes:
    refresh_interval: "5m"
    stale_threshold: "10m"
    api_key: "${GOOGLE_ROUTES_API_KEY}"
  caltrans_feeds:
    chain_controls:
      refresh_interval: "15m"  # Less frequent, changes slowly
      url: "https://quickmap.dot.ca.gov/data/cc.kml"
    lane_closures:
      refresh_interval: "10m"
      url: "https://quickmap.dot.ca.gov/data/lcs2way.kml"
    chp_incidents:
      refresh_interval: "5m"   # More frequent, incidents change quickly
      url: "https://quickmap.dot.ca.gov/data/chp-only.kml"
  monitored_routes:
    - name: "I-5 Seattle to Portland"
      id: "i5-sea-pdx"
      origin:
        latitude: 47.6062
        longitude: -122.3321
      destination:
        latitude: 45.5152
        longitude: -122.6784
    - name: "US-101 Coastal Route"  
      id: "us101-coastal"
      origin:
        latitude: 46.9741
        longitude: -124.1060  
      destination:
        latitude: 43.7749
        longitude: -124.5087

weather:
  refresh_interval: "5m"
  stale_threshold: "10m"
  openweather_api_key: "${OPENWEATHER_API_KEY}"
  locations:
    - id: "seattle"
      name: "Seattle, WA"
      lat: 47.6062
      lon: -122.3321
    - id: "portland"  
      name: "Portland, OR"
      lat: 45.5152
      lon: -122.6784